
public class CustOpEditorUtils {
    static let symbolsDict = ["alpha": "α",
                              "ALPHA": "Α",
                              "beta": "β",
                              "BETA": "Β",
                              "gamma": "γ",
                              "GAMMA": "Γ",
                              "delta": "δ",
                              "DELTA": "Δ",
                              "epsilon": "ε",
                              "EPSILON": "Ε",
                              "zeta": "ζ",
                              "ZETA": "Ζ",
                              "eta": "η",
                              "ETA": "Η",
                              "theta": "θ",
                              "THETA": "Θ",
                              "iota": "ι",
                              "IOTA": "Ι",
                              "kappa": "κ",
                              "KAPPA": "Κ",
                              "lamda": "λ",
                              "LAMDA": "Λ",
                              "gmu": "μ",
                              "GMU": "Μ",
                              "gnu": "ν",
                              "GNU": "Ν",
                              "gxi": "ξ",
                              "GXI": "Ξ",
                              "omicron": "ο",
                              "OMICRON": "Ο",
                              "gpi": "π",
                              "GPI": "Π",
                              "rho": "ρ",
                              "RHO": "Ρ",
                              "sigma": "σ",
                              "SIGMA": "Σ",
                              "tau": "τ",
                              "TAU": "Τ",
                              "upsilon": "υ",
                              "UPSILON": "Υ",
                              "phi": "φ",
                              "PHI": "Φ",
                              "chi": "χ",
                              "CHI": "Χ",
                              "psi": "ψ",
                              "PSI": "Ψ",
                              "omega": "ω",
                              "OMEGA": "Ω"
    ]
}